import os

Import('env')
Import('prefix')
Import('destdir')

data = """
	defimg.png
	dirimg.png
	icon.png
	mov.png
	mapdir.png
	mapdirs.png
	FreeSans.ttf
	vs.c
	vs_fish.c
	fs.c
	effprg.pl
""".split()

env['DATADIR'] = os.path.join(prefix,'share',env['APPNAME'])
datadir = destdir + env['DATADIR']
env.Install(datadir, [data])
install_data = env.Alias('install-data', datadir)

Export('install_data')
