import os

Import('env')
Import('prefix')
Import('destdir')

data = """
	defimg.png
	FreeSans.ttf
	vs_fish.c
	fs.c
""".split()

env['DATADIR'] = os.path.join(prefix,'share',env['APPNAME'])
datadir = destdir + env['DATADIR']
env.Install(datadir, [data])
install_data = env.Alias('install-data', datadir)

Export('install_data')
