Import('env')

main_sources = """
	main.c
	sdl.c
	gl.c
	dpl.c
	load.c
	support.c
	img.c
	cfg.c
""".split()

sources = env.Object(main_sources)

prog = env.Program('../slideshowgl', sources, install=True)

Export('sources')
