Import('env')

sources = """
	main.c
	sdl.c
	gl.c
	dpl.c
	load.c
	support.c
	img.c
	cfg.c
""".split()

objects = env.Object(sources)

prog = env.Program('../slideshowgl', objects, install=True)
#env.Install('/usr/bin',prog)
#env.Alias('install','/usr/bin')
