Import('env')
Import('prefix')

sources = """
	main.c
	sdl.c
	gl.c
	dpl.c
	load.c
	support.c
	img.c
	cfg.c
""".split()

objects = env.Object(sources)

prog = env.Program('../slideshowgl', objects, install=True)

env.Install(prefix + '/bin',prog)
install_bin = env.Alias('install-bin',prefix + '/bin')

Export('install_bin')
